global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]   # make sure Alertmanager is running here

rule_files:
  - "alerts.yml"                        # your alerts file lives next to prometheus.yml

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  # Windows Exporter on this same PC
  - job_name: "windows_exporter"
    static_configs:
      - targets: ["localhost:9182"]
        labels:
          app: "windows-exporter"

  # Blackbox Exporter (HTTP checks)
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]   # which probe module to use
    static_configs:
      - targets:
          - http://example.com
          - https://google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115   # Blackbox Exporter address
